//
// Created by Tomáš Tatyrek on 09/03/2025.
//

#ifndef TT2D_LOGGER_H
#define TT2D_LOGGER_H

#include <SDL3/SDL.h>
#include <string>

#include "defines.h"

namespace TT2D {

	enum LogCategory {
		LOG_CATEGORY_APPLICAION = SDL_LOG_CATEGORY_APPLICATION,
		LOG_CATEGORY_ERROR = SDL_LOG_CATEGORY_ERROR,
		LOG_CATEGORY_ASSERT = SDL_LOG_CATEGORY_ASSERT,
		LOG_CATEGORY_SYSTEM = SDL_LOG_CATEGORY_SYSTEM,
		LOG_CATEGORY_AUDIO = SDL_LOG_CATEGORY_AUDIO,
		LOG_CATEGORY_VIDEO = SDL_LOG_CATEGORY_VIDEO,
		LOG_CATEGORY_RENDER = SDL_LOG_CATEGORY_RENDER,
		LOG_CATEGORY_INPUT = SDL_LOG_CATEGORY_INPUT,
		LOG_CATEGORY_TEST = SDL_LOG_CATEGORY_TEST,
		LOG_CATEGORY_GPU = SDL_LOG_CATEGORY_GPU,
		LOG_CATEGORY_CUSTOM = SDL_LOG_CATEGORY_CUSTOM
	};

	enum LogPriority {
		LOG_PRIORITY_INVALID = SDL_LOG_PRIORITY_INVALID,
		LOG_PRIORITY_TRACE = SDL_LOG_PRIORITY_TRACE,
		LOG_PRIORITY_VERBOSE = SDL_LOG_PRIORITY_VERBOSE,
		LOG_PRIORITY_DEBUG = SDL_LOG_PRIORITY_DEBUG,
		LOG_PRIORITY_INFO = SDL_LOG_PRIORITY_INFO,
		LOG_PRIORITY_WARN = SDL_LOG_PRIORITY_WARN,
		LOG_PRIORITY_ERROR = SDL_LOG_PRIORITY_ERROR,
		LOG_PRIORITY_CRITICAL = SDL_LOG_PRIORITY_CRITICAL,
		LOG_PRIORITY_COUNT = SDL_LOG_PRIORITY_COUNT
	};

	void log(LogPriority priority, LogCategory category, TT2D_LOG_MESSAGE_TYPE message);
	void logInvalid(LogCategory category, TT2D_LOG_MESSAGE_TYPE message);
	//TODO: Continue
}
#endif//TT2D_LOGGER_H
